services:
  - type: web
    name: anime2d-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:app --config src/gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GROQ_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: src/app.py
