services:
  - type: web
    name: anime2d-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: cd src && PYTHONPATH=$PYTHONPATH:. gunicorn app:app --timeout 300 --workers 1 --threads 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GROQ_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: src/app.py
