services:
  - type: web
    name: anime2d-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      cd src
      PYTHONPATH=$PYTHONPATH:. \
      gunicorn \
        --config ../src/gunicorn_config.py \
        app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: "5000"
