services:
  - type: web
    name: anime2d-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      PYTHONPATH=$PYTHONPATH:$(pwd) \
      gunicorn \
        --config src/gunicorn_config.py \
        src.app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: "5000"
