name: Keep Manim LLM Service Alive

on:
    workflow_dispatch:      # Allow "Run workflow" button
    schedule:
      - cron: "* * * * *"  # Run every minute

jobs:
  ping-llm-service:
    runs-on: ubuntu-latest
    steps:
      - name: Ping LLM Service Health Endpoint
        run: |
          curl -fsS https://manim-llm-service.onrender.com/health \
            || echo "LLM Service ping failed at $(date)"
